services:
  mobilebankingussd.api:
    image: ${DOCKER_REGISTRY-}mobilebankingussdapi
    container_name: MobileBankingUSSD.API  
    build:
      context: .
      dockerfile: MobileBankingUSSD.API/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    networks:
      - postgres
  
  mobilebankingussd.database:
    image: postgres
    container_name: MobileBankingUSSD.Database
    hostname: mobilebankingussd-database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bankingdb

    volumes:
        - db-container-volume:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
    
    
  pgadmin:
    container_name: MobileBanking.PGAdmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-volume:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - mobilebankingussd.database
        
  mobilebankingussd.seq:
    image: datalust/seq:latest
    container_name: MobileBankingUSSD.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"


  mobilebankingussd.redis:
    image: redis
    container_name: MobileBankingUSSD.Redis
    restart: always
    ports:
        - "6379:6379"

  mobilebankingussd.queue:
    image: rabbitmq:management-alpine
    container_name: MobileBanking.Queue
    hostname: mobilebankingussd-queue
    volumes:
      - ./.containers/queue/data:/var/lib/rabbitmq
      - ./.containers/queue/log:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    ports:
      - "5672:5672"
      - "15672:15762"

networks:
  postgres:
    driver: bridge

volumes:
  db-container-volume:
  pgadmin-volume:
